### ISSUE TITLE
Problem When run ng serve

### ISSUE THREAD

**Issue by micro24** [AndreasFagschlunger/o2xfs-angular#1]
Hi
Thank you for your project, I have a problem when I run ng serve i get below error:
"ERROR in src/app/app-routing.module.ts(3,32): error TS2307: Cannot find module 'operator'."
please guide me , how can i resolve my problem.

Best Regards

**Comment by AndreasFagschlunger** [comment]
Hi! I'm sorry to say that the code is in such a early stage, that I can't provide support at this time. The basic idea was to create a angular app instead of the old javax.swing based O²Xfs Operator. The whole server part is still missing and I'm currently so busy that I don't find time to work on any of my O²Xfs projects.

So this repo contains only some UI code and basic angular services how things could work, more like a playground for me.

Altough, the problem may occur due to the fact that lazy loading isn't working. I don't know why, but there is a workaround, I think something like this:

https://github.com/angular/angular-cli/issues/10673#issuecomment-423665996

Best regards,
Andreas Fagschlunger
